public interface ITriggerDispatcher {

void dummyMethod();

/*  void bulkBefore();
    
    void bulkAfter();
    
    void andFinally();
    
    void beforeInsert(TriggerParameters tp);
    
    void beforeUpdate(TriggerParameters tp);
    
    void beforeDelete(TriggerParameters tp);
    
    void afterInsert(TriggerParameters tp);
    
    void afterUpdate(TriggerParameters tp);
    
    void afterDelete(TriggerParameters tp);
    
    void afterUnDelete(TriggerParameters tp);
    */
}